### ISSUE TITLE
converting ModelLoader to netcoreapp3.1 fails at runtime

### ISSUE THREAD

**Issue by jackfoxy** [aardvark-platform/aardvark.docs#28]
see branch https://github.com/jackfoxy/aardvark.docs/tree/modelloader3.1/src

```
Assimp.AssimpException
  HResult=0x80131500
  Message=Error loading unmanaged library from path: C:\Users\jackf\AppData\Local\Temp\aardvark-native\AssimpNet-969d1624-35de-e8ae-f27b-d0ea28a223a6-64\Assimp64.dll, see inner exception for details.
The specified module could not be found. (0x8007007E)
  Source=AssimpNet
  StackTrace:
   at Assimp.Unmanaged.AssimpLibraryWindowsImplementation.NativeLoadLibrary(String path)
   at Assimp.Unmanaged.AssimpLibraryImplementation.LoadAssimpLibrary(String path)
   at Assimp.Unmanaged.AssimpLibrary.LoadLibrary()
   at Assimp.Unmanaged.AssimpLibrary.LoadIfNotLoaded()
   at Assimp.Unmanaged.AssimpLibrary.CreatePropertyStore()
   at Assimp.AssimpContext.CreateConfigs()
   at Assimp.AssimpContext.PrepareImport()
   at Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)
   at Aardvark.SceneGraph.IO.Loader.AssimpModule.loadFrom(String file, PostProcessSteps postProcessingFlags)
   at Aardvark.SceneGraph.IO.Loader.Assimp.Load(String fileName, FSharpOption`1 flags)
   at Program.main(String[] argv) in C:\Users\jackf\GitRepos\Aardvark.Docs\src\ModelLoader\Program.fs:line 24

Inner Exception 1:
FileNotFoundException: The specified module could not be found. (0x8007007E)
```

**Comment by haraldsteinlechner** [comment]
fixed in https://github.com/aardvark-platform/aardvark.docs/commit/31f910c7755f14914c08b4b89d34c937515ac1c0
does it work for you now?

**Comment by jackfoxy** [comment]
ModelLoader is still netcoreapp2.0 in the latest `master`. I was attempting to build and run in 3.1, but no matter. It still fails at runtime for me. With somewhat different output.

```
 0: unpacking native dependencies for assimp
 0: Failed to unpack native assimp dependencies. Did you forget Aardvark.Init()? Make sure Aardvark.SceneGraph.IO.dll is in your output directory.
 0: initializing aardvark ....................................................
 0:   System Information:
 0:     OSVersion: Microsoft Windows NT 10.0.19041.0
 0:     SystemArchitecture: 64-bit
 0:     Environment.Version: 4.0.30319.42000
 0:     WARNING: could not load native library: Assimp64.dll Error=0
 0:   Loading plugins ................................................ 0.026 s
 0:   initializing PixImageDevil ..................................... 0.015 s
 0:   initializing ModModule .................................................
 0:     initializing mod system ...................................... 0.000 s
 0:   initializing ModModule ......................................... 0.001 s
 0:   initializing NewAg ............................................. 0.008 s
 0:   initializing Ag ................................................ 0.000 s
 0:   initializing SceneGraphCompletenessCheck ....................... 0.076 s
 0: initializing aardvark ............................................ 0.218 s
 0: initializing OpenGL runtime ..............................................
 0:   vendor:   "NVIDIA Corporation"
 0:   renderer: "Quadro P4200 with Max-Q Design/PCIe/SSE2"
 0:   version:  OpenGL 4.3.0 / GLSL 4.3
 0: initializing OpenGL runtime ...................................... 0.164 s

Unhandled Exception: Assimp.AssimpException: Error loading unmanaged library from path: Assimp64.dll, see inner exception for details.
The specified module could not be found. (Exception from HRESULT: 0x8007007E) ---> System.IO.FileNotFoundException: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   --- End of inner exception stack trace ---
   at Assimp.Unmanaged.AssimpLibraryWindowsImplementation.NativeLoadLibrary(String path) in D:\Development\assimp-net\src\AssimpNet\Unmanaged\AssimpLibrary.cs:line 1683
   at Assimp.Unmanaged.AssimpLibraryImplementation.LoadAssimpLibrary(String path) in D:\Development\assimp-net\src\AssimpNet\Unmanaged\AssimpLibrary.cs:line 1541
   at Assimp.Unmanaged.AssimpLibrary.LoadLibrary() in D:\Development\assimp-net\src\AssimpNet\Unmanaged\AssimpLibrary.cs:line 143
   at Assimp.Unmanaged.AssimpLibrary.CreatePropertyStore() in D:\Development\assimp-net\src\AssimpNet\Unmanaged\AssimpLibrary.cs:line 505
   at Assimp.AssimpContext.CreateConfigs() in D:\Development\assimp-net\src\AssimpNet\AssimpContext.cs:line 1006
   at Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags) in D:\Development\assimp-net\src\AssimpNet\AssimpContext.cs:line 285
   at Aardvark.SceneGraph.IO.Loader.AssimpModule.loadFrom(String file, PostProcessSteps postProcessingFlags) in C:\Users\Schorsch\Development\aardvark.rendering\src\Aardvark.SceneGraph.IO\IO.fs:line 774
   at Program.main(String[] argv) in C:\Users\jackf\GitRepos\Aardvark.Docs\src\ModelLoader\Program.fs:line 27
```
